name: pypi release

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  MAX_PYTHON_V: 3.12

jobs:
  tests:
    uses: ./.github/workflows/test.yaml
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.MAX_PYTHON_V }}
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-build.txt
        hatch build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
